### ISSUE TITLE
'future' is not installed on worker

### ISSUE THREAD

**Issue by kjfuller06** [cran/blockCV#1]
I'm trying to run the vignette for blockCV and when I try to run the spatialAutoRange() function with doParallel = TRUE, I get this error:

`Error: Initialization of plan() failed, because the test future used for validation failed. The reason was: Package 'future' is not installed on worker (r_version: 4.0.2 (2020-06-22); platform: x86_64-w64-mingw32 (64-bit); os: Windows 10 x64 build 18363; hostname: WSL552KK13)`

The issue seems to be that the cluster is not inheriting loaded packages. When I change doParallel to FALSE, the function runs without errors.

**Comment by kjfuller06** [comment]
#https://github.com/HenrikBengtsson/future/issues/219

**Comment by kjfuller06** [comment]
#219

**Comment by kjfuller06** [comment]
This thread describes a similar issue
https://github.com/HenrikBengtsson/future/issues/219

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!
